### ISSUE TITLE
Add snake game in any language

### ISSUE THREAD

**Issue by mayankwalia** [mayankwalia/HacktoberFest-22#1]

**Comment by Ishikasaraf20** [comment]
hey @mayankwalia can you assign this issue to me i can work on it

**Comment by mayankwalia** [comment]
Yes you can proceed. @Ishikasaraf20

**Comment by Ishikasaraf20** [comment]
Hey @mayankwalia I've added snake game in python and javascript kindly review the changes in the PR and if you found this helpful kindly merge it to your main branch

**Comment by KanjiZain** [comment]
I would like to contribute game in python language using pygame

**Comment by Mayureshkaulwar** [comment]
can you assign to me?
